# Generated by Django 5.2.7 on 2025-10-10 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_it', models.CharField(max_length=200, verbose_name='Nome (Italiano)')),
                ('nome_en', models.CharField(blank=True, max_length=200, verbose_name='Nome (Inglese)')),
                ('nome_fr', models.CharField(blank=True, max_length=200, verbose_name='Nome (Francese)')),
                ('nome_es', models.CharField(blank=True, max_length=200, verbose_name='Nome (Spagnolo)')),
                ('slug', models.SlugField(blank=True, help_text='Lascia vuoto per generazione automatica dal nome italiano', max_length=100, unique=True, verbose_name='Slug URL')),
                ('immagine_copertina', models.ImageField(blank=True, null=True, upload_to='cataloghi/copertine/', verbose_name='Immagine  Copertina')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Modifica')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cataloghi_creati', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cataloghi_modificati', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Catalogo',
                'verbose_name_plural': 'Cataloghi',
                'ordering': ['slug'],
            },
        ),
    ]
