# Generated by Django 5.2.7 on 2025-10-14 19:48

import catalogo.models
import django.db.models.deletion
import filer.fields.file
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0017_image__transparent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cartella', models.CharField(blank=True, help_text='Es: A31 Perle in plastica, FS46 Materiali', max_length=250, verbose_name='Nome Cartella')),
                ('nome_cartella_sort', models.CharField(blank=True, editable=False, max_length=250, verbose_name='Nome Cartella Sort')),
                ('file_upload_diretto', models.FileField(blank=True, help_text='Per aggiornamenti veloci: carica file direttamente qui', null=True, upload_to=catalogo.models.cartella_upload_path, verbose_name='Upload Diretto')),
                ('tipo_file', models.CharField(blank=True, editable=False, max_length=10, verbose_name='Tipo File')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Modifica')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartelle_create', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('file_da_filer', filer.fields.file.FilerFileField(blank=True, help_text='Per upload massivi: prima carica su Filer, poi seleziona qui', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartelle_catalogo', to='filer.file', verbose_name='Seleziona da Media Manager')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartelle_modificate', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Cartella Catalogo',
                'verbose_name_plural': 'Cartelle Catalogo',
                'ordering': ['nome_cartella_sort'],
            },
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_it', models.CharField(max_length=200, verbose_name='Nome (Italiano)')),
                ('nome_en', models.CharField(blank=True, max_length=200, verbose_name='Nome (Inglese)')),
                ('nome_fr', models.CharField(blank=True, max_length=200, verbose_name='Nome (Francese)')),
                ('nome_es', models.CharField(blank=True, max_length=200, verbose_name='Nome (Spagnolo)')),
                ('slug', models.SlugField(blank=True, help_text='Lascia vuoto per generazione automatica dal nome italiano', max_length=100, unique=True, verbose_name='Slug URL')),
                ('immagine_copertina', models.ImageField(blank=True, null=True, upload_to='cataloghi/copertine/', verbose_name='Immagine  Copertina')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Modifica')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cataloghi_creati', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cataloghi_modificati', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Catalogo',
                'verbose_name_plural': 'Cataloghi',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='CatalogoCartella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.IntegerField(default=0, verbose_name='Ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cartella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cataloghi_root', to='catalogo.cartelle', verbose_name='Cartella')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartelle_root_associate', to='catalogo.catalogo', verbose_name='Catalogo')),
            ],
            options={
                'verbose_name': 'Catalogo-Cartella',
                'verbose_name_plural': 'Catalogo-Cartelle',
                'ordering': ['catalogo', 'ordine'],
                'unique_together': {('catalogo', 'cartella')},
            },
        ),
        migrations.AddField(
            model_name='catalogo',
            name='cartelle_root',
            field=models.ManyToManyField(blank=True, related_name='cataloghi', through='catalogo.CatalogoCartella', to='catalogo.cartelle', verbose_name='File Root'),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_it', models.CharField(max_length=200, verbose_name='Nome (Italiano)')),
                ('nome_en', models.CharField(blank=True, max_length=200, verbose_name='Nome (Inglese)')),
                ('nome_fr', models.CharField(blank=True, max_length=200, verbose_name='Nome (Francese)')),
                ('nome_es', models.CharField(blank=True, max_length=200, verbose_name='Nome (Spagnolo)')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Modifica')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorie', to='catalogo.catalogo', verbose_name='Catalogo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorie_create', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sottocategorie', to='catalogo.categoria', verbose_name='Categoria Padre')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorie_modificate', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['catalogo__nome_it', 'nome_it'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaCartella',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.IntegerField(default=0, verbose_name='Ordine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cartella', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie_associate', to='catalogo.cartelle', verbose_name='Cartella')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartelle_associate', to='catalogo.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria-Cartella',
                'verbose_name_plural': 'Categoria-Cartelle',
                'ordering': ['categoria', 'ordine'],
                'unique_together': {('categoria', 'cartella')},
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='cartelle',
            field=models.ManyToManyField(blank=True, related_name='categorie', through='catalogo.CategoriaCartella', to='catalogo.cartelle', verbose_name='File Categorizzati'),
        ),
    ]
