# Generated by Django 5.2.7 on 2025-10-10 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_it', models.CharField(max_length=200, verbose_name='Nome (Italiano)')),
                ('nome_en', models.CharField(blank=True, max_length=200, verbose_name='Nome (Inglese)')),
                ('nome_fr', models.CharField(blank=True, max_length=200, verbose_name='Nome (Francese)')),
                ('nome_es', models.CharField(blank=True, max_length=200, verbose_name='Nome (Spagnolo)')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Modifica')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorie', to='catalogo.catalogo', verbose_name='Catalogo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorie_create', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sottocategorie', to='catalogo.categoria', verbose_name='Categoria Padre')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorie_modificate', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'ordering': ['catalogo', 'nome_it'],
            },
        ),
    ]
