# Generated by Django 5.2.7 on 2025-10-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartelle',
            options={'ordering': ['nome_cartella_sort'], 'verbose_name': 'Cartella', 'verbose_name_plural': 'Cartelle'},
        ),
    ]
