# Generated by Django 5.2.7 on 2025-10-13 12:38

import catalogo.models
import django.db.models.deletion
import filer.fields.file
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_categoria'),
        ('filer', '0017_image__transparent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartelleCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cartella', models.CharField(help_text='Es: A31 Perle in plastica, FS46 Materiali', max_length=250, verbose_name='Nome Cartella')),
                ('nome_cartella_sort', models.CharField(blank=True, editable=False, max_length=250, verbose_name='Nome Cartella Sort')),
                ('file_upload_diretto', models.FileField(blank=True, help_text='Per aggiornamenti veloci: carica file direttamente qui', null=True, upload_to=catalogo.models.cartella_upload_path, verbose_name='Upload Diretto')),
                ('tipo_file', models.CharField(blank=True, editable=False, max_length=10, verbose_name='Tipo File')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Modifica')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartelle', to='catalogo.categoria', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartelle_create', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('file_da_filer', filer.fields.file.FilerFileField(blank=True, help_text='Per upload massivi: prima carica su Filer, poi seleziona qui', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartelle_catalogo', to='filer.file', verbose_name='Seleziona da Media Manager')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartelle_modificate', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Cartella Catalogo',
                'verbose_name_plural': 'Cartelle Catalogo',
                'ordering': ['categoria__catalogo', 'categoria', 'nome_cartella_sort'],
            },
        ),
    ]
