# Generated by Django 5.2.7 on 2025-10-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_cartellecatalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartellecatalogo',
            name='nome_cartella',
            field=models.CharField(blank=True, help_text='Es: A31 Perle in plastica, FS46 Materiali', max_length=250, verbose_name='Nome Cartella'),
        ),
    ]
